
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package jcup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEC_PROG = 37;
  public static final int OP_MENIG = 16;
  public static final int ASIG_TIPO = 18;
  public static final int OP_MAYIG = 15;
  public static final int COR_CIE = 6;
  public static final int SEC_ENDPROG = 38;
  public static final int WRITE = 31;
  public static final int OP_DIV = 9;
  public static final int CTE_ENT = 19;
  public static final int AND = 33;
  public static final int SEC_END = 36;
  public static final int CTE_BIN = 21;
  public static final int OR = 34;
  public static final int PAR_ABR = 3;
  public static final int OP_IGU = 14;
  public static final int SEC_DEC = 35;
  public static final int BEGIN = 23;
  public static final int OP_MUL = 10;
  public static final int IF = 27;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int ASIG_VAR = 17;
  public static final int ASIG_FL = 39;
  public static final int error = 1;
  public static final int COMA = 42;
  public static final int COR_ABR = 5;
  public static final int PERCENT = 32;
  public static final int OP_MEN = 12;
  public static final int ASIG_STR = 41;
  public static final int ENDIF = 30;
  public static final int ELSE = 29;
  public static final int OP_SUM = 7;
  public static final int CTE_STR = 22;
  public static final int ASIG_INT = 40;
  public static final int WHILE = 25;
  public static final int THEN = 28;
  public static final int OP_MAY = 11;
  public static final int END = 24;
  public static final int CTE_REA = 20;
  public static final int OP_DIST = 13;
  public static final int PAR_CIE = 4;
  public static final int DO = 26;
  public static final int OP_RES = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "PAR_ABR",
  "PAR_CIE",
  "COR_ABR",
  "COR_CIE",
  "OP_SUM",
  "OP_RES",
  "OP_DIV",
  "OP_MUL",
  "OP_MAY",
  "OP_MEN",
  "OP_DIST",
  "OP_IGU",
  "OP_MAYIG",
  "OP_MENIG",
  "ASIG_VAR",
  "ASIG_TIPO",
  "CTE_ENT",
  "CTE_REA",
  "CTE_BIN",
  "CTE_STR",
  "BEGIN",
  "END",
  "WHILE",
  "DO",
  "IF",
  "THEN",
  "ELSE",
  "ENDIF",
  "WRITE",
  "PERCENT",
  "AND",
  "OR",
  "SEC_DEC",
  "SEC_END",
  "SEC_PROG",
  "SEC_ENDPROG",
  "ASIG_FL",
  "ASIG_INT",
  "ASIG_STR",
  "COMA"
  };
}

